name: Continuous Integration

on:
  push:
    branches:
    - "feature/**"
    paths-ignore:
    - 'docs/**'
    - '.gitignore'
    - 'LICENSE'
    - '**.txt'
    - '**.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - 'docs/**'
    - '.gitignore'
    - 'LICENSE'
    - '**.txt'
    - '**.md'
  workflow_dispatch:


jobs:
  continuous-integration:
    uses: Traffic-Tech/Traffic.Tech.GitHub.Core.Workflows/.github/workflows/continuous-integration-orchestrator.yml@master
    with:
      project-path: "./"
      node-version: "22"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}